name       : enchant16
version    : 1.6.0
release    : 1
source     :
    - http://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz : 2fac9e7be7e9424b2c5570d8affe568db39f7572c10ed48d4e13cddf03f7097f
license    : LGPL-2.1-or-later
component  : spelling
summary    : enchant16 is the 1.6 series of the spell check library wrapper program
description: |
    enchant16 is the 1.6 series of the spell check library wrapper program
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
setup      : |
    %configure --with-system-myspell=yes \
               --with-myspell-dir=/usr/share/hunspell \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/enchant/enchant.ordering $installdir/usr/share/enchant/enchant16.ordering
